
name: "CI-CD"

on: push

env:
  PYTHON_VERSION: 3.8

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Set Stanza version
        run: |
          echo "STANZA_VERSION=$(cat requirements.txt | grep -E -i "^stanza" >> $GITHUB_ENV
      - name: Cache Stanzas
        uses: actions/cache@v3
        with:
          path: ~/stanza_resources
          key: ${{ runner.os }}-stanza-resources-${{ env.STANZA_VERSION }}
      - name: Set NLTK version
        run: |
          echo "NLTK_VERSION=$(cat requirements.txt | grep -E -i "^nltk" >> $GITHUB_ENV
      - name: Cache nltk
        uses: actions/cache@v3
        with:
          path: ~/nltk_data
          key: ${{ runner.os }}-nltk-data-${{ env.NLTK_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with Pytest
        run: |
          python resources_installation.py
          pytest tests --cov=. --cov-fail-under=75 --cov-report term-missing
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Pylint
        run: |
          pylint ./**/*.py
  bump_version:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [tests, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [bump_version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Push Image
        run: |
          docker login ${{ vars.REGISTRY_ENDPOINT }} -u userdoesnotmatter -p ${{ secrets.TOKEN }}
          docker build . --compress --tag ${{ vars.REGISTRY_ENDPOINT }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.IMAGE_NAME }}:${{ vars.VERSION }}
          docker push ${{ vars.REGISTRY_ENDPOINT }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.IMAGE_NAME }}:${{ vars.VERSION }}
      - name: Deploy container
        run: |
          CONTAINER_ID=$(sed -e 's/^"//' -e 's/"$//' <<<$(curl -X GET -H "X-Auth-Token: ${{ secrets.TOKEN}}" "https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/" | jq -e '.containers[] | select(.name|test("${{ vars.CONTAINER_NAME }}"))'.id))
          curl \
            -X POST \
            -H "X-Auth-Token: ${{ secrets.TOKEN }}" \
            -d "{}" \
            "https://api.scaleway.com/containers/${{ vars.SCW_API_VERSION }}/regions/fr-par/containers/$CONTAINER_ID/deploy" \
            | jq 'del(."environment_variables")'
