name: "[CD] Push Image to Docker Hub"

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches-ignore:
      - "chore"

env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Push Image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }} . --compress
          docker tag ${{ secrets.IMAGE_NAME }} ${{ secrets.USERNAME }}/${{ secrets.REPO_NAME }}:${{ secrets.VERSION }}
          docker push ${{ secrets.TAG }}