name: "[CD] Push Image to Docker Hub"

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "chore"

env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Push Image
        run: |
          docker logout
          sudo docker login  index.docker.io --username "${{ secrets.USERNAME }}" -p "${{ secrets.PASSWORD }}"
          docker build -t ${{ secrets.IMAGE_NAME }} . --compress
          docker tag ${{ secrets.IMAGE_NAME }} ${{ secrets.USERNAME }}/${{ secrets.REPOSITORY_NAME }}:${{ secrets.VERSION }}
          docker push ${{ secrets.TAG }}