
name: "[CI] Tests"

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches-ignore:
      - "chore"

env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with Pytest
        run: |
          python resources_installation.py
          pytest tests --cov=. --cov-fail-under=75 --cov-report term-missing